CREATE TABLE `content_briefs` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`client_id` integer NOT NULL,
	`title` text NOT NULL,
	`content_type` text DEFAULT 'service_page' NOT NULL,
	`funnel_stage` text DEFAULT 'consideration' NOT NULL,
	`search_intent` text DEFAULT 'commercial' NOT NULL,
	`primary_topic` text NOT NULL,
	`supporting_topics` text DEFAULT '[]' NOT NULL,
	`recommended_url` text DEFAULT '' NOT NULL,
	`objective` text DEFAULT '' NOT NULL,
	`audience` text DEFAULT '' NOT NULL,
	`outline` text DEFAULT '[]' NOT NULL,
	`questions` text DEFAULT '[]' NOT NULL,
	`evidence` text DEFAULT '[]' NOT NULL,
	`internal_links` text DEFAULT '[]' NOT NULL,
	`call_to_action` text DEFAULT '' NOT NULL,
	`metadata` text DEFAULT '{}' NOT NULL,
	`schema_type` text DEFAULT '' NOT NULL,
	`acceptance_checklist` text DEFAULT '[]' NOT NULL,
	`success_metrics` text DEFAULT '[]' NOT NULL,
	`status` text DEFAULT 'draft' NOT NULL,
	`approved_at` text,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL
);
