type ClientInput={website:string;niche:string;location:string};
type Finding={title:string;evidence:string;impact:string;recommendation:string;severity:string;confidence:string};
type PageScan={url:string;title:string;description:string;h1s:string[];tel:boolean;form:boolean;analytics:boolean;schema:boolean;canonical:boolean;viewport:boolean};

const MAX_PAGES=8, MAX_HTML=1_500_000;
function clean(value:string){return value.replace(/<[^>]+>/g," ").replace(/&(?:amp|#38);/gi,"&").replace(/\s+/g," ").trim()}
function content(html:string,pattern:RegExp){return clean(html.match(pattern)?.[1]||"")}
function present(html:string,pattern:RegExp){return pattern.test(html)}
function safeStart(value:string){let url:URL;try{url=new URL(value.match(/^https?:\/\//i)?value:`https://${value}`)}catch{throw new Error("Enter a valid public website URL")};if(!["http:","https:"].includes(url.protocol))throw new Error("Only http and https websites can be scanned");const host=url.hostname.toLowerCase();if(host==="localhost"||host.endsWith(".local")||/^127\.|^10\.|^192\.168\.|^169\.254\.|^0\./.test(host))throw new Error("Private network addresses cannot be scanned");url.hash="";return url}
function priority(url:URL){const p=url.pathname.toLowerCase();return /service|roof|location|area|contact|about|repair|install|commercial|residential/.test(p)?0:/blog|news|project|case/.test(p)?2:1}
function links(html:string,base:URL,origin:string){const found:string[]=[];for(const match of html.matchAll(/<a\b[^>]+href=["']([^"'#]+)["']/gi)){try{const u=new URL(match[1],base);u.hash="";if(u.origin!==origin||!["http:","https:"].includes(u.protocol)||/\.(?:pdf|jpg|jpeg|png|gif|webp|svg|zip|docx?|xlsx?)$/i.test(u.pathname))continue;u.search="";found.push(u.toString())}catch{}}return [...new Set(found)].sort((a,b)=>priority(new URL(a))-priority(new URL(b)))}
async function fetchPage(url:URL){const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),12000);let response:Response;try{response=await fetch(url.toString(),{redirect:"follow",signal:controller.signal,headers:{"user-agent":"AgencyCommandAudit/2.0"}})}finally{clearTimeout(timeout)}if(!response.ok)throw new Error(`HTTP ${response.status}`);if(!(response.headers.get("content-type")||"").includes("text/html"))throw new Error("not HTML");const html=(await response.text()).slice(0,MAX_HTML);const final=new URL(response.url||url);return {html,final}}
function inspect(html:string,url:URL):PageScan{return {url:url.toString(),title:content(html,/<title[^>]*>([\s\S]*?)<\/title>/i),description:(html.match(/<meta[^>]+name=["']description["'][^>]+content=["']([^"']*)/i)?.[1]||html.match(/<meta[^>]+content=["']([^"']*)["'][^>]+name=["']description["']/i)?.[1]||"").trim(),h1s:[...html.matchAll(/<h1\b[^>]*>([\s\S]*?)<\/h1>/gi)].map(m=>clean(m[1])).filter(Boolean),tel:present(html,/<a[^>]+href=["']tel:/i),form:present(html,/<form\b/i),analytics:present(html,/googletagmanager\.com|gtag\s*\(|google-analytics\.com/i),schema:present(html,/application\/ld\+json/i),canonical:present(html,/<link[^>]+rel=["']canonical["']/i),viewport:present(html,/<meta[^>]+name=["']viewport["']/i)}}

export async function scanWebsite(client:ClientInput){
 const start=safeStart(client.website),origin=start.origin,queue=[start.toString()],seen=new Set<string>(),pages:PageScan[]=[],failed:string[]=[];
 while(queue.length&&pages.length<MAX_PAGES){const next=queue.shift()!;if(seen.has(next))continue;seen.add(next);try{const {html,final}=await fetchPage(new URL(next));if(final.origin!==origin){if(pages.length===0)throw new Error("The homepage redirected to another website");continue}pages.push(inspect(html,final));for(const link of links(html,final,origin))if(!seen.has(link)&&!queue.includes(link))queue.push(link)}catch(error){if(pages.length===0)throw new Error(error instanceof Error&&error.name==="AbortError"?"The website could not be reached within 12 seconds":"The website could not be scanned");failed.push(new URL(next).pathname)}}
 if(!pages.length)throw new Error("No HTML pages could be scanned");
 const date=new Date().toISOString().slice(0,10),label=(p:PageScan)=>{const path=new URL(p.url).pathname;return path==="/"?"Homepage":path},evidence=(p:PageScan,detail:string)=>`${label(p)} · ${new URL(p.url).hostname} · ${date} · ${detail}`;
 const findings:Finding[]=[];
 findings.push({title:`Crawl coverage: ${pages.length} page${pages.length===1?"":"s"} inspected`,evidence:`Live crawl · ${pages.map(label).join(" · ")}${failed.length?` · ${failed.length} page(s) unreachable`:""}`,impact:"The audit can distinguish repeated site-wide patterns from isolated page issues.",recommendation:pages.length<3?"Add or expose crawlable links to the main service, location and contact pages.":"Review the recorded page set before approving the audit; add any commercially important pages the crawler did not discover.",severity:pages.length<3?"medium":"low",confidence:"confirmed crawl coverage"});
 const missingTitle=pages.filter(p=>!p.title),oddTitle=pages.filter(p=>p.title&&(p.title.length<25||p.title.length>65)),missingDesc=pages.filter(p=>!p.description),badH1=pages.filter(p=>p.h1s.length!==1),noAction=pages.filter(p=>!p.tel&&!p.form),noSchema=pages.filter(p=>!p.schema),noCanonical=pages.filter(p=>!p.canonical),noViewport=pages.filter(p=>!p.viewport);
 const add=(items:PageScan[],title:string,detail:(p:PageScan)=>string,impact:string,recommendation:string,severity:string,confidence="confirmed on scanned pages")=>{if(items.length)findings.push({title,evidence:items.slice(0,5).map(p=>evidence(p,detail(p))).join(" | ")+(items.length>5?` | +${items.length-5} more`:""),impact,recommendation,severity,confidence})};
 add(missingTitle,"Pages are missing title tags",()=>"no <title> detected","Search engines and visitors receive a weaker summary of those pages.","Write a distinct title for every commercial page using its service, location and purpose.","high");
 add(oddTitle,"Page titles need refinement",p=>`title is ${p.title.length} characters: “${p.title.slice(0,80)}”`,"Important search results may communicate too little or be truncated.","Rewrite affected titles clearly around the page purpose; avoid mechanical keyword stuffing.","medium");
 add(missingDesc,"Pages are missing meta descriptions",()=>"description meta tag not detected","Search snippets may be less persuasive and less controlled.","Add a specific description explaining the offer and next action on each affected page.","medium");
 add(badH1,"Heading hierarchy needs attention",p=>`${p.h1s.length} H1 headings detected${p.h1s.length?`: ${p.h1s.slice(0,2).join(" | ")}`:""}`,"The primary message and page hierarchy may be unclear.","Use one descriptive primary heading on each page, followed by logical H2 sections.","medium");
 add(noAction,"Commercial pages lack a direct enquiry action",()=>"no telephone link or HTML form found","High-intent visitors may not see an immediate route to enquire.","Add a prominent enquiry action and verify it across mobile and desktop.","high","confirmed in page HTML; visual position requires review");
 if(!pages.some(p=>p.analytics))findings.push({title:"Google measurement tag was not detected",evidence:`Live crawl · ${pages.length} pages · no public gtag, Tag Manager or Analytics reference found`,impact:"Website enquiries and campaign outcomes may not be measurable.",recommendation:"Verify the consent-aware analytics implementation and test every important conversion.",severity:"high",confidence:"confirmed in scanned HTML"});
 add(noSchema,"Structured data was not detected on scanned pages",()=>"no JSON-LD block found","Search engines receive fewer explicit facts about the business and page content.",`Add valid structured data appropriate to this ${client.niche.toLowerCase()} business and each page's visible content.`,"low");
 add(noCanonical,"Canonical links were not detected",()=>"no canonical link element found","Duplicate URL signals may be less explicit to search engines.","Add a self-referencing canonical after confirming each preferred URL.","low");
 add(noViewport,"Mobile viewport declaration is missing",()=>"viewport meta tag not detected","Affected pages may not render predictably on mobile devices.","Add the standard responsive viewport declaration and complete a mobile usability review.","high");
 return {finalUrl:pages[0].url,pageCount:pages.length,pages:pages.map(p=>({url:p.url,title:p.title,h1Count:p.h1s.length})),failed,signals:{analytics:pages.some(p=>p.analytics),schema:pages.some(p=>p.schema),viewport:pages.every(p=>p.viewport)},findings};
}
