"use client";
/* eslint-disable @typescript-eslint/no-explicit-any */
import { useEffect, useMemo, useState } from "react";
type Connection={provider:string;accountLabel:string;metrics:any;lastSyncedAt:string|null};
type Outcome={id:number;occurredAt:string;source:string;contactName:string;stage:string;value:number;notes:string};
type MonthlyReport={id:number;period:string;summary:string;completedWork:string[];results:string[];issues:string[];priorities:string[];status:string;approvedAt:string|null;createdAt:string};
const Badge=({children,tone="green"}:{children:React.ReactNode;tone?:string})=><span className={`pill ${tone}`}>{children}</span>;
const money=(n:number)=>new Intl.NumberFormat("en-GB",{style:"currency",currency:"GBP",maximumFractionDigits:0}).format(n);

export default function Reporting({client,connections,findings,setView,flash}:{client?:{id:number;name:string;website:string;niche:string;location:string};connections:Connection[];findings:{severity:string}[];setView:(view:any)=>void;flash:(message:string)=>void}){
 const [outcomes,setOutcomes]=useState<Outcome[]>([]),[reports,setReports]=useState<MonthlyReport[]>([]),[saving,setSaving]=useState(false),[reporting,setReporting]=useState(false),[form,setForm]=useState({occurredAt:new Date().toISOString().slice(0,10),source:"Organic search",contactName:"",stage:"lead",value:""});
 const load=()=>client&&Promise.all([fetch(`/api/attribution?clientId=${client.id}`),fetch(`/api/reports?clientId=${client.id}`)]).then(async([a,b])=>{if(!a.ok||!b.ok)throw new Error();setOutcomes((await a.json()).outcomes||[]);setReports((await b.json()).reports||[])}).catch(()=>flash("Could not load performance records"));
 // Reload only when the selected client changes.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 useEffect(()=>{load()},[client?.id]);
 const save=async()=>{if(!client)return flash("Add a client first");setSaving(true);try{const r=await fetch("/api/attribution",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...form,clientId:client.id,value:Number(form.value)||0})}),d=await r.json();if(!r.ok)return flash(d.error||"Could not save outcome");setForm({...form,contactName:"",value:""});await load();flash("Lead outcome saved")}finally{setSaving(false)}};
 const google=connections.find(x=>x.provider==="google"),meta=connections.find(x=>x.provider==="meta"),clarity=connections.find(x=>x.provider==="clarity"),gm=google?.metrics||{},mm=meta?.metrics||{},cm=clarity?.metrics||{};
 const organic=Number(gm.searchConsole?.clicks||0),users=Number(gm.ga4?.users||0),friction=Number(cm.rageClicks||0)+Number(cm.deadClicks||0)+Number(cm.quickBacks||0),live=connections.filter(x=>x.lastSyncedAt),high=findings.filter(x=>x.severity==="high").length;
 const totals=useMemo(()=>({leads:outcomes.length,qualified:outcomes.filter(x=>["qualified","proposal","won"].includes(x.stage)).length,proposals:outcomes.filter(x=>["proposal","won"].includes(x.stage)).length,wins:outcomes.filter(x=>x.stage==="won").length,revenue:outcomes.filter(x=>x.stage==="won").reduce((n,x)=>n+x.value,0)}),[outcomes]);
 const spend=Number(gm.googleAds?.spend||0)+Number(mm.spend||0),cac=totals.wins?spend/totals.wins:null,roi=spend&&totals.revenue?((totals.revenue-spend)/spend)*100:null;
 const insights=[live.length?`${live.length} source${live.length===1?" is":"s are"} supplying dated performance evidence.`:"No private performance source has been imported yet.",organic||users?`Organic search supplied ${organic.toLocaleString()} clicks; GA4 supplied ${users.toLocaleString()} users.`:"Connect Google to establish the organic and on-site baseline.",outcomes.length?`${totals.qualified} of ${totals.leads} recorded leads reached qualified or later; ${totals.wins} became won customers.`:"Record lead outcomes to connect enquiries with sales results.",friction?`${friction.toLocaleString()} aggregated Clarity friction signals need page-level investigation in Clarity.`:"No imported Clarity friction signal is available for this period."];
 const createReport=async()=>{if(!client)return flash("Add a client first");setReporting(true);try{const period=new Date().toISOString().slice(0,7),completedWork=[live.length?`${live.length} performance sources reviewed`:"Performance source setup reviewed",findings.length?`${findings.length} website audit findings monitored`:"Website evidence reviewed"],results=[`${totals.leads} leads, ${totals.qualified} qualified and ${totals.wins} won recorded`,`${money(totals.revenue)} won revenue recorded`,organic||users?`${organic.toLocaleString()} organic clicks and ${users.toLocaleString()} GA4 users imported`:"Organic and on-site baseline not imported"],issues=[high?`${high} high-priority audit findings remain`:"No high-priority audit finding is currently recorded",!live.length?"No dated private performance import is available":""].filter(Boolean),priorities=[high?"Resolve high-priority conversion and technical findings":"Keep audit evidence current",!live.length?"Connect and import the required performance sources":"Refresh source data before the next review","Update every lead outcome through won or lost"],summary=`${client.name} recorded ${totals.qualified} qualified leads, ${totals.wins} won customers and ${money(totals.revenue)} won revenue for the evidence currently held in the CRM. ${high?`${high} high-priority audit issues still need action.`:"No high-priority audit issue is currently recorded."}`;const r=await fetch("/api/reports",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({clientId:client.id,period,summary,completedWork,results,issues,priorities,evidenceSnapshot:{generatedAt:new Date().toISOString(),sourceSyncs:live.map(x=>({provider:x.provider,lastSyncedAt:x.lastSyncedAt})),totals,spend,roi,highFindings:high}})}),d=await r.json();if(!r.ok)return flash(d.error||"Could not create report");await load();flash("Monthly report draft saved")}finally{setReporting(false)}};
 const approve=async(id:number)=>{const r=await fetch("/api/reports",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,status:"approved"})}),d=await r.json();if(!r.ok)return flash(d.error||"Could not approve report");await load();flash("Monthly report approved")};
 return <div className="page"><div className="client-head"><div className="logo">{client?.name?.split(" ").map(x=>x[0]).join("").slice(0,2)||"NR"}</div><div><span>{client?`${client.niche} · ${client.location||"Location not supplied"}`:"Roofing · London"}</span><h2>{client?.name||"Northstar Roofing"}</h2><small>{client?.website||"northstarroofing.co.uk"}</small></div><Badge tone={outcomes.length?"green":"amber"}>{outcomes.length?`${outcomes.length} outcomes recorded`:"Attribution baseline needed"}</Badge></div>
 <div className="intro"><div><h2>Performance and revenue</h2><p>Connect marketing evidence to qualified leads, proposals, won customers and recorded revenue.</p></div><div className="reportactions"><button className="primary" disabled={reporting} onClick={createReport}>{reporting?"Creating…":"Create monthly report"}</button><button className="secondary" onClick={()=>window.print()}>Print</button></div></div>
 <div className="reportmetrics">{[["Qualified leads",totals.qualified,"CRM outcomes"],["Proposals",totals.proposals,"CRM outcomes"],["Won revenue",money(totals.revenue),"Recorded sales"],["Acquisition cost",cac===null?"—":money(cac),cac===null?"Needs spend + wins":"Blended paid spend"]].map(x=><article key={String(x[0])}><span>{x[0]}</span><strong>{typeof x[1]==="number"?x[1].toLocaleString():x[1]}</strong><small>{x[2]}</small></article>)}</div>
 <div className="split reportgrid"><section className="panel"><span className="overline">Revenue funnel</span><h3>Lead-to-customer outcomes</h3><div className="funnel">{[["All leads",totals.leads],["Qualified",totals.qualified],["Proposal",totals.proposals],["Won",totals.wins]].map((x,i)=><div key={String(x[0])}><span>{x[0]}</span><b>{x[1]}</b><i><em style={{width:`${totals.leads?Math.max(5,Number(x[1])/totals.leads*100):0}%`}}/></i>{i>0&&<small>{totals.leads?`${Math.round(Number(x[1])/totals.leads*100)}% of leads`:"No baseline"}</small>}</div>)}</div></section><section className="panel copilot"><div className="orb">✦</div><span className="overline">Guarded ROI</span><h3>{roi===null?"Complete the attribution baseline":`${roi.toFixed(0)}% recorded paid ROI`}</h3><p>{roi===null?"ROI appears only when both imported paid spend and won revenue are available.":`${money(totals.revenue)} won revenue minus ${money(spend)} imported paid spend. This excludes fees, margin and offline costs.`}</p><button onClick={()=>setView(roi===null?"data":"reporting")}>{roi===null?"Review required sources":"Review outcome records"} →</button><footer><strong>Evidence boundary</strong><span>Source is manually recorded per outcome. Cross-device identity and assisted attribution are not inferred.</span></footer></section></div>
 <section className="panel outcomeentry"><div><span className="overline">Outcome capture</span><h3>Record a lead or sales-stage change</h3><p>Use the known lead source. Choose “Unknown” when it cannot be verified.</p></div><div className="outcomeform"><label>Date<input type="date" value={form.occurredAt} onChange={e=>setForm({...form,occurredAt:e.target.value})}/></label><label>Source<select value={form.source} onChange={e=>setForm({...form,source:e.target.value})}><option>Organic search</option><option>Google Ads</option><option>Meta Ads</option><option>Google Business Profile</option><option>Referral</option><option>Direct</option><option>Unknown</option></select></label><label>Contact / reference<input placeholder="Optional" value={form.contactName} onChange={e=>setForm({...form,contactName:e.target.value})}/></label><label>Stage<select value={form.stage} onChange={e=>setForm({...form,stage:e.target.value})}><option value="lead">Lead</option><option value="qualified">Qualified</option><option value="proposal">Proposal</option><option value="won">Won customer</option><option value="lost">Lost</option></select></label><label>Revenue (£)<input type="number" min="0" placeholder="Only if known" value={form.value} onChange={e=>setForm({...form,value:e.target.value})}/></label><button className="primary" disabled={saving} onClick={save}>{saving?"Saving…":"Save outcome"}</button></div></section>
 <section className="panel outcomelist"><div className="panelhead"><div><span className="overline">CRM evidence</span><h3>Recent lead outcomes</h3></div><Badge tone="slate">Manual, traceable records</Badge></div>{outcomes.length?outcomes.slice(0,12).map(x=><div key={x.id}><span>{new Date(`${x.occurredAt}T12:00:00`).toLocaleDateString()}</span><strong>{x.contactName||"Unnamed lead"}</strong><span>{x.source}</span><Badge tone={x.stage==="won"?"green":x.stage==="lost"?"red":"blue"}>{x.stage}</Badge><b>{x.value?money(x.value):"—"}</b></div>):<p className="emptyoutcomes">No outcomes recorded yet. Add the first enquiry or sales-stage update above.</p>}</section>
 <div className="split reportgrid"><section className="panel"><span className="overline">Evidence summary</span><h3>What the data says</h3><div className="insights">{insights.map((item,i)=><article key={item}><b>{i+1}</b><p>{item}</p></article>)}</div></section><section className="panel copilot"><div className="orb">⌁</div><span className="overline">Evidence health</span><h3>{high?`${high} high-priority findings remain`:"Audit evidence is clear"}</h3><p>{high?"Resolve conversion blockers before interpreting channel efficiency.":"Keep outcome stages updated so revenue reporting remains useful."}</p><button onClick={()=>setView(high?"audit":"data")}>Review supporting evidence →</button></section></div>
 <section className="panel reporthistory"><div className="panelhead"><div><span className="overline">Monthly review</span><h3>Saved client reports</h3></div><Badge tone={reports.length?"green":"slate"}>{reports.length?`${reports.length} saved`:"No reports yet"}</Badge></div>{reports.length?reports.map(r=><article key={r.id}><header><div><strong>{new Date(`${r.period}-02T12:00:00`).toLocaleDateString("en-GB",{month:"long",year:"numeric"})}</strong><span>Created {new Date(r.createdAt).toLocaleDateString()}</span></div><Badge tone={r.status==="approved"?"green":"amber"}>{r.status}</Badge></header><p>{r.summary}</p><div className="reportcolumns"><div><b>Results</b>{r.results.slice(0,3).map(x=><span key={x}>✓ {x}</span>)}</div><div><b>Next priorities</b>{r.priorities.slice(0,3).map(x=><span key={x}>→ {x}</span>)}</div></div>{r.status!=="approved"?<button className="primary" onClick={()=>approve(r.id)}>Approve report</button>:<small>Approved {r.approvedAt?new Date(r.approvedAt).toLocaleString():""} · evidence snapshot locked</small>}</article>):<p className="emptyoutcomes">Create the first monthly report from the current saved evidence.</p>}</section></div>;
}
