import { sql } from "drizzle-orm";
import { integer, sqliteTable, text } from "drizzle-orm/sqlite-core";
export const clients=sqliteTable("clients",{id:integer("id").primaryKey({autoIncrement:true}),name:text("name").notNull(),website:text("website").notNull(),niche:text("niche").notNull(),location:text("location").notNull().default(""),stage:text("stage").notNull().default("lead"),createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`)});
export const findings=sqliteTable("findings",{id:integer("id").primaryKey({autoIncrement:true}),clientId:integer("client_id").notNull(),title:text("title").notNull(),evidence:text("evidence").notNull().default(""),impact:text("impact").notNull().default(""),recommendation:text("recommendation").notNull().default(""),severity:text("severity").notNull().default("medium"),confidence:text("confidence").notNull().default("hypothesis"),approval:text("approval").notNull().default("pending")});
export const tasks=sqliteTable("tasks",{id:integer("id").primaryKey({autoIncrement:true}),clientId:integer("client_id").notNull(),title:text("title").notNull(),instructions:text("instructions").notNull().default(""),definitionOfDone:text("definition_of_done").notNull().default(""),status:text("status").notNull().default("ready"),dueDate:text("due_date"),ownerRole:text("owner_role").notNull().default("owner")});
export const strategies=sqliteTable("strategies",{id:integer("id").primaryKey({autoIncrement:true}),clientId:integer("client_id").notNull(),objective:text("objective").notNull(),channels:text("channels").notNull(),roadmap:text("roadmap").notNull(),status:text("status").notNull().default("draft"),createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`)});
export const proposals=sqliteTable("proposals",{id:integer("id").primaryKey({autoIncrement:true}),clientId:integer("client_id").notNull(),title:text("title").notNull(),summary:text("summary").notNull().default(""),objective:text("objective").notNull().default(""),deliverables:text("deliverables").notNull().default("[]"),schedule:text("schedule").notNull().default("[]"),clientResponsibilities:text("client_responsibilities").notNull().default("[]"),assumptions:text("assumptions").notNull().default("[]"),exclusions:text("exclusions").notNull().default("[]"),kpis:text("kpis").notNull().default("[]"),setupFee:integer("setup_fee").notNull().default(0),monthlyFee:integer("monthly_fee").notNull().default(3000),adSpend:integer("ad_spend").notNull().default(0),currency:text("currency").notNull().default("GBP"),termMonths:integer("term_months").notNull().default(3),validUntil:text("valid_until").notNull().default(""),status:text("status").notNull().default("draft"),sentAt:text("sent_at"),acceptedAt:text("accepted_at"),acceptedBy:text("accepted_by"),acceptanceNote:text("acceptance_note"),createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`)});
export const leadOutcomes=sqliteTable("lead_outcomes",{id:integer("id").primaryKey({autoIncrement:true}),clientId:integer("client_id").notNull(),occurredAt:text("occurred_at").notNull(),source:text("source").notNull().default("unknown"),contactName:text("contact_name").notNull().default(""),stage:text("stage").notNull().default("lead"),value:integer("value").notNull().default(0),notes:text("notes").notNull().default(""),createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`)});
export const monthlyReports=sqliteTable("monthly_reports",{id:integer("id").primaryKey({autoIncrement:true}),clientId:integer("client_id").notNull(),period:text("period").notNull(),summary:text("summary").notNull(),completedWork:text("completed_work").notNull().default("[]"),results:text("results").notNull().default("[]"),issues:text("issues").notNull().default("[]"),priorities:text("priorities").notNull().default("[]"),evidenceSnapshot:text("evidence_snapshot").notNull().default("{}"),status:text("status").notNull().default("draft"),approvedAt:text("approved_at"),createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`)});
export const onboardingItems=sqliteTable("onboarding_items",{id:integer("id").primaryKey({autoIncrement:true}),clientId:integer("client_id").notNull(),category:text("category").notNull(),label:text("label").notNull(),detail:text("detail").notNull().default(""),status:text("status").notNull().default("needed"),notes:text("notes").notNull().default(""),requestedAt:text("requested_at"),completedAt:text("completed_at"),createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`)});
export const contentBriefs=sqliteTable("content_briefs",{id:integer("id").primaryKey({autoIncrement:true}),clientId:integer("client_id").notNull(),title:text("title").notNull(),contentType:text("content_type").notNull().default("service_page"),funnelStage:text("funnel_stage").notNull().default("consideration"),searchIntent:text("search_intent").notNull().default("commercial"),primaryTopic:text("primary_topic").notNull(),supportingTopics:text("supporting_topics").notNull().default("[]"),recommendedUrl:text("recommended_url").notNull().default(""),objective:text("objective").notNull().default(""),audience:text("audience").notNull().default(""),outline:text("outline").notNull().default("[]"),questions:text("questions").notNull().default("[]"),evidence:text("evidence").notNull().default("[]"),internalLinks:text("internal_links").notNull().default("[]"),callToAction:text("call_to_action").notNull().default(""),metadata:text("metadata").notNull().default("{}"),schemaType:text("schema_type").notNull().default(""),acceptanceChecklist:text("acceptance_checklist").notNull().default("[]"),successMetrics:text("success_metrics").notNull().default("[]"),status:text("status").notNull().default("draft"),approvedAt:text("approved_at"),createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`)});
export const dataConnections=sqliteTable("data_connections",{
 id:integer("id").primaryKey({autoIncrement:true}),clientId:integer("client_id").notNull(),provider:text("provider").notNull(),status:text("status").notNull().default("connected"),
 accessToken:text("access_token").notNull(),refreshToken:text("refresh_token").notNull().default(""),expiresAt:integer("expires_at").notNull().default(0),
 accountLabel:text("account_label").notNull().default(""),propertyId:text("property_id").notNull().default(""),metrics:text("metrics").notNull().default("{}"),
 lastSyncedAt:text("last_synced_at"),createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`)
});
