import { and,eq } from "drizzle-orm";
import { getDb } from "../../../../../db";
import { dataConnections } from "../../../../../db/schema";
import { open,seal } from "../../../../google-auth";
/* eslint-disable @typescript-eslint/no-explicit-any */

async function json(url:string,token:string,init?:RequestInit){const r=await fetch(url,{...init,headers:{authorization:`Bearer ${token}`,"content-type":"application/json",...(init?.headers||{})}});const body=await r.json();if(!r.ok)throw new Error(`Google import failed (${r.status})`);return body as any}
async function optionalJson(url:string,token:string){try{return await json(url,token)}catch{return null}}
async function adsJson(url:string,token:string,init?:RequestInit){const developerToken=process.env.GOOGLE_ADS_DEVELOPER_TOKEN;if(!developerToken)return null;try{const r=await fetch(url,{...init,headers:{authorization:`Bearer ${token}`,"developer-token":developerToken,"content-type":"application/json",...(process.env.GOOGLE_ADS_LOGIN_CUSTOMER_ID?{"login-customer-id":process.env.GOOGLE_ADS_LOGIN_CUSTOMER_ID.replace(/-/g,"")}:{})}}),body=await r.json();if(!r.ok)return null;return body as any}catch{return null}}
async function importAds(token:string){
 const empty={status:process.env.GOOGLE_ADS_DEVELOPER_TOKEN?"unavailable":"setup_required",customerCount:0,customer:"No Google Ads account selected",customerId:"",currency:"",campaigns:0,impressions:0,clicks:0,cost:0,conversions:0};
 if(!process.env.GOOGLE_ADS_DEVELOPER_TOKEN)return empty;
 const version=process.env.GOOGLE_ADS_API_VERSION||"v22",root=`https://googleads.googleapis.com/${version}`;
 const accessible=await adsJson(`${root}/customers:listAccessibleCustomers`,token),resources:string[]=accessible?.resourceNames||[];
 for(const resource of resources){const customerId=resource.split("/").pop()||"";if(!customerId)continue;const query="SELECT customer.descriptive_name, customer.currency_code, customer.manager, campaign.id, metrics.impressions, metrics.clicks, metrics.cost_micros, metrics.conversions FROM campaign WHERE segments.date DURING LAST_30_DAYS AND campaign.status != 'REMOVED'";const rows=await adsJson(`${root}/customers/${customerId}/googleAds:searchStream`,token,{method:"POST",body:JSON.stringify({query})});if(!Array.isArray(rows))continue;const results=rows.flatMap((batch:any)=>batch.results||[]);if(results[0]?.customer?.manager)continue;return {status:"connected",customerCount:resources.length,customer:results[0]?.customer?.descriptiveName||`Google Ads ${customerId}`,customerId,currency:results[0]?.customer?.currencyCode||"",campaigns:new Set(results.map((r:any)=>r.campaign?.id).filter(Boolean)).size,impressions:results.reduce((n:number,r:any)=>n+Number(r.metrics?.impressions||0),0),clicks:results.reduce((n:number,r:any)=>n+Number(r.metrics?.clicks||0),0),cost:results.reduce((n:number,r:any)=>n+Number(r.metrics?.costMicros||0),0)/1e6,conversions:results.reduce((n:number,r:any)=>n+Number(r.metrics?.conversions||0),0)} }
 return {...empty,status:resources.length?"api_access_required":"no_accounts",customerCount:resources.length};
}
function sumSeries(series:any[]=[]){return series.reduce((total,item)=>total+(item.timeSeries?.datedValues||[]).reduce((n:number,v:any)=>n+Number(v.value||0),0),0)}
export async function POST(request:Request){
 const {clientId}=await request.json() as {clientId?:number};if(!clientId)return Response.json({error:"clientId is required"},{status:400});
 const db=getDb(),rows=await db.select().from(dataConnections).where(and(eq(dataConnections.clientId,clientId),eq(dataConnections.provider,"google"))).limit(1),connection=rows[0];
 if(!connection)return Response.json({error:"Connect Google first"},{status:409});
 try{
  let token=await open(connection.accessToken),expiresAt=connection.expiresAt;
  if(expiresAt<Date.now()+60000){if(!connection.refreshToken)throw new Error("Reconnect Google to refresh access");const refresh=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({client_id:process.env.GOOGLE_CLIENT_ID!,client_secret:process.env.GOOGLE_CLIENT_SECRET!,refresh_token:await open(connection.refreshToken),grant_type:"refresh_token"})});const t=await refresh.json() as {access_token?:string;expires_in?:number};if(!refresh.ok||!t.access_token)throw new Error("Google access expired; reconnect required");token=t.access_token;expiresAt=Date.now()+(t.expires_in||3600)*1000}
  const [gsc,ga,profileAccounts,googleAds]=await Promise.all([json("https://www.googleapis.com/webmasters/v3/sites",token),json("https://analyticsadmin.googleapis.com/v1beta/accountSummaries?pageSize=200",token),optionalJson("https://mybusinessaccountmanagement.googleapis.com/v1/accounts",token),importAds(token)]);
  const site=(gsc.siteEntry||[]).find((s:any)=>s.permissionLevel!=="siteUnverifiedUser")||gsc.siteEntry?.[0];
  const property=(ga.accountSummaries||[]).flatMap((a:any)=>(a.propertySummaries||[]).map((p:any)=>({...p,account:a.displayName}))).find((p:any)=>p.property);
  const end=new Date(),start=new Date(Date.now()-28*86400000),date=(d:Date)=>d.toISOString().slice(0,10);let search={clicks:0,impressions:0,ctr:0,position:0},analytics={users:0,sessions:0,conversions:0};
  if(site?.siteUrl){const report=await json(`https://www.googleapis.com/webmasters/v3/sites/${encodeURIComponent(site.siteUrl)}/searchAnalytics/query`,token,{method:"POST",body:JSON.stringify({startDate:date(start),endDate:date(end),rowLimit:1})});if(report.rows?.[0])search=report.rows[0]}
  if(property?.property){const report=await json(`https://analyticsdata.googleapis.com/v1beta/${property.property}:runReport`,token,{method:"POST",body:JSON.stringify({dateRanges:[{startDate:"28daysAgo",endDate:"yesterday"}],metrics:[{name:"activeUsers"},{name:"sessions"},{name:"keyEvents"}]})});const v=report.rows?.[0]?.metricValues||[];analytics={users:Number(v[0]?.value||0),sessions:Number(v[1]?.value||0),conversions:Number(v[2]?.value||0)}}
  let businessProfile:any={status:profileAccounts?"available":"unavailable",locationCount:0,location:"No Business Profile location",websiteClicks:0,callClicks:0,directionRequests:0,mapsImpressions:0,searchImpressions:0};
  const account=profileAccounts?.accounts?.find((a:any)=>a.verificationState==="VERIFIED")||profileAccounts?.accounts?.[0];
  if(account?.name){const locations=await optionalJson(`https://mybusinessbusinessinformation.googleapis.com/v1/${account.name}/locations?readMask=name,title,storefrontAddress,websiteUri,metadata&pageSize=100`,token);const list=locations?.locations||[],location=list[0];businessProfile={...businessProfile,status:"connected",account:account.accountName||account.name,locationCount:list.length,location:location?.title||"No location selected",address:location?.storefrontAddress||null,website:location?.websiteUri||"",mapsUri:location?.metadata?.mapsUri||""};if(location?.name){const q=new URLSearchParams();for(const metric of ["WEBSITE_CLICKS","CALL_CLICKS","BUSINESS_DIRECTION_REQUESTS","BUSINESS_IMPRESSIONS_DESKTOP_MAPS","BUSINESS_IMPRESSIONS_MOBILE_MAPS","BUSINESS_IMPRESSIONS_DESKTOP_SEARCH","BUSINESS_IMPRESSIONS_MOBILE_SEARCH"])q.append("dailyMetrics",metric);const sd={year:start.getUTCFullYear(),month:start.getUTCMonth()+1,day:start.getUTCDate()},ed={year:end.getUTCFullYear(),month:end.getUTCMonth()+1,day:end.getUTCDate()};for(const [k,v] of Object.entries(sd))q.set(`dailyRange.start_date.${k}`,String(v));for(const [k,v] of Object.entries(ed))q.set(`dailyRange.end_date.${k}`,String(v));const perf=await optionalJson(`https://businessprofileperformance.googleapis.com/v1/${location.name}:fetchMultiDailyMetricsTimeSeries?${q}`,token),series=perf?.multiDailyMetricTimeSeries||[];const value=(name:string)=>sumSeries(series.filter((x:any)=>x.dailyMetric===name));businessProfile={...businessProfile,websiteClicks:value("WEBSITE_CLICKS"),callClicks:value("CALL_CLICKS"),directionRequests:value("BUSINESS_DIRECTION_REQUESTS"),mapsImpressions:value("BUSINESS_IMPRESSIONS_DESKTOP_MAPS")+value("BUSINESS_IMPRESSIONS_MOBILE_MAPS"),searchImpressions:value("BUSINESS_IMPRESSIONS_DESKTOP_SEARCH")+value("BUSINESS_IMPRESSIONS_MOBILE_SEARCH")}}}
  const metrics={period:"Last 28 days",searchConsole:{site:site?.siteUrl||"No verified property",...search},ga4:{property:property?.displayName||"No property",...analytics},businessProfile,googleAds},now=new Date().toISOString();
  await db.update(dataConnections).set({accessToken:await seal(token),expiresAt,accountLabel:property?.account||"Google account",propertyId:property?.property||site?.siteUrl||"",metrics:JSON.stringify(metrics),lastSyncedAt:now,status:"connected"}).where(eq(dataConnections.id,connection.id));return Response.json({metrics,lastSyncedAt:now});
 }catch(error){return Response.json({error:error instanceof Error?error.message:"Google import failed"},{status:502})}
}
